.libPaths(c('outputs/original_proposal_20260928_v01/R_library','.Rlib',.libPaths()))
suppressPackageStartupMessages({library(survey);library(jsonlite);library(lpSolve)})
options(survey.lonely.psu='fail',survey.adjust.domain.lonely=FALSE)
ROOT<-'/Volumes/Elements/NHANES_asthma_ra_extension_20261008_fresh_v1';BASE<-'outputs/year_extension_20261008_v01';O<-file.path(BASE,'pooled')
wr<-function(x,n)write.csv(x,file.path(O,paste0(n,'.csv')),row.names=FALSE,na='')
d<-readRDS(file.path(ROOT,'pooled/derived/analysis_frame.rds'));kn<-read.csv(file.path(BASE,'prepandemic/supplement/knots.csv'))
rcs<-function(x,k){pos<-function(t)pmax(t,0)^3;(pos(x-k[1])-(k[3]-k[1])/(k[3]-k[2])*pos(x-k[2])+(k[2]-k[1])/(k[3]-k[2])*pos(x-k[3]))/(k[3]-k[1])^2}
for(v in c('age','pir','bmi'))d[[paste0(v,'_nl')]]<-rcs(d[[v]],as.numeric(kn[kn$variable==v,2:4]))
d$cycle<-factor(d$year);d$era<-factor(ifelse(d$year==2021,'latest','prepandemic'),levels=c('prepandemic','latest'))
broad<-d[d$design_valid,];wide<-svydesign(ids=~SDMVPSU,strata=~SDMVSTRA,weights=~analysis_weight,data=broad,nest=TRUE);des<-subset(wide,eligible)
forms<-list(P1=asthma~ra+age+sex+race+education+pir+bmi+smoking+cycle,P2=asthma~ra+age+age_nl+sex+race+education+pir+pir_nl+bmi+smoking+cycle)
forms$I1<-update(forms$P1,.~.+ra:era);forms$I2<-update(forms$P2,.~.+ra:era)
fits<-list();diags<-list();est<-list();checks<-list()
for(n in names(forms)){
 warn<-character();m<-withCallingHandlers(svyglm(forms[[n]],des,family=quasibinomial(),control=glm.control(maxit=100,epsilon=1e-12)),warning=function(w){warn<<-c(warn,conditionMessage(w));invokeRestart('muffleWarning')})
 X<-model.matrix(m);y<-model.response(model.frame(m));A<-sweep(X,2,pmax(apply(abs(X),2,max),1),'/')*(2*y-1);p<-ncol(X)
 lpfit<-lp('max',c(colSums(A),-colSums(A)),rbind(cbind(A,-A),rep(1,2*p)),c(rep('>=',nrow(A)),'<='),c(rep(0,nrow(A)),1))
 valid<-m$converged&&m$rank==ncol(X)&&lpfit$status==0&&lpfit$objval<=1e-7&&all(is.finite(vcov(m)))
 diags[[n]]<-data.frame(model=n,n=nrow(X),events=sum(y),rank=m$rank,parameters=p,converged=m$converged,lp_status=lpfit$status,lp_objective=lpfit$objval,condition_number=kappa(scale(X[,-1]),exact=TRUE),df=degf(des),status=if(valid)'estimable' else 'not_estimable',warnings=paste(unique(warn),collapse=' | '))
 fits[[n]]<-m;b<-coef(m);se<-sqrt(diag(vcov(m)));nu<-degf(des)
 for(term in c('ra',grep('ra:era',names(b),value=TRUE)))est[[paste(n,term)]]<-data.frame(model=n,term=term,estimand=if(term=='ra'&&n %in% c('P1','P2'))'pooled_common_OR' else if(term=='ra')'prepandemic_OR_in_interaction_model' else 'OR_ratio_latest_over_prepandemic',n=nrow(X),beta=b[term],se=se[term],estimate=if(valid)exp(b[term]) else NA,lower=if(valid)exp(b[term]-qt(.975,nu)*se[term]) else NA,upper=if(valid)exp(b[term]+qt(.975,nu)*se[term]) else NA,p=if(valid)2*pt(abs(b[term]/se[term]),nu,lower.tail=FALSE) else NA,df=nu,status=if(valid)'estimable' else 'not_estimable',formula=paste(deparse(forms[[n]]),collapse=' '))
 if(n %in% c('I1','I2')&&valid){tt<-regTermTest(m,~ra:era,df=nu,method='Wald');j<-grep('ra:era',names(b));Fval<-as.numeric(b[j]^2/vcov(m)[j,j]);stopifnot(length(j)==1,abs(Fval-as.numeric(tt$Ftest))<1e-10)
 checks[[n]]<-data.frame(model=n,F=Fval,df1=1,df2=nu,p=as.numeric(tt$p),independent_p=pf(Fval,1,nu,lower.tail=FALSE),pass=abs(as.numeric(tt$p)-pf(Fval,1,nu,lower.tail=FALSE))<1e-12)
 }
 cat('Pooled',n,'valid',valid,'\n')
}
wr(do.call(rbind,diags),'pooling_model_diagnostics');wr(do.call(rbind,est),'pooling_models');wr(do.call(rbind,checks),'period_interactions')
contrib<-lapply(sort(unique(d$year)),function(yr){q<-d[d$year==yr,];z<-q[q$eligible,];data.frame(year=yr,label=unique(q$cycle_label),n_demo=nrow(q),n_pre_covariate=sum(q$pre_covariate),n_complete=nrow(z),completion_rate=nrow(z)/sum(q$pre_covariate),ra_n=sum(z$ra),asthma_n=sum(z$asthma),joint_n=sum(z$ra*z$asthma),weighted_sample_share=sum(z$analysis_weight)/sum(d$analysis_weight[d$eligible]),min_weight=min(z$analysis_weight),max_weight=max(z$analysis_weight))})
wr(do.call(rbind,contrib),'cycle_contributions')
saveRDS(fits,file.path(ROOT,'pooled/derived/pooling_models.rds'))
write_json(list(technical_estimability=if(all(vapply(diags,function(x)x$status=='estimable',logical(1))))'pass' else 'needs evidence',scientific_pooling_approval='not inferred from P values; interpretation review required',missing_period_represented=FALSE),file.path(O,'pooling_gate.json'),pretty=TRUE,auto_unbox=TRUE)
print(do.call(rbind,est))
